// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBoLjC1EdrAE-BLTT-YPt73Br7j-A5-HSw',
    appId: '1:684123174149:web:a474bbd3bdde28df54336c',
    messagingSenderId: '684123174149',
    projectId: 'sign-language-translator-6e778',
    authDomain: 'sign-language-translator-6e778.firebaseapp.com',
    storageBucket: 'sign-language-translator-6e778.firebasestorage.app',
    measurementId: 'G-1WWD08VCHZ',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDvCSxAq1jM6pf_VQtOWsGErZwpC60b79o',
    appId: '1:684123174149:android:a543668fde5b22ec54336c',
    messagingSenderId: '684123174149',
    projectId: 'sign-language-translator-6e778',
    storageBucket: 'sign-language-translator-6e778.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCCmLI6haHL3JfDvOxZnFgi1aST7dVPXEw',
    appId: '1:684123174149:ios:af0183fb490f5f8454336c',
    messagingSenderId: '684123174149',
    projectId: 'sign-language-translator-6e778',
    storageBucket: 'sign-language-translator-6e778.firebasestorage.app',
    iosBundleId: 'com.example.signaspeech',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCCmLI6haHL3JfDvOxZnFgi1aST7dVPXEw',
    appId: '1:684123174149:ios:af0183fb490f5f8454336c',
    messagingSenderId: '684123174149',
    projectId: 'sign-language-translator-6e778',
    storageBucket: 'sign-language-translator-6e778.firebasestorage.app',
    iosBundleId: 'com.example.signaspeech',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBoLjC1EdrAE-BLTT-YPt73Br7j-A5-HSw',
    appId: '1:684123174149:web:ce682f6d283fe5eb54336c',
    messagingSenderId: '684123174149',
    projectId: 'sign-language-translator-6e778',
    authDomain: 'sign-language-translator-6e778.firebaseapp.com',
    storageBucket: 'sign-language-translator-6e778.firebasestorage.app',
    measurementId: 'G-T07NFHPX47',
  );
}
